# Generated by Django 4.0.3 on 2022-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(default=0)),
                ('fetch', models.CharField(max_length=6)),
                ('decode', models.CharField(max_length=6)),
                ('execute', models.CharField(max_length=6)),
                ('memory', models.CharField(max_length=6)),
                ('write_back', models.CharField(max_length=6)),
            ],
        ),
    ]
